
FROM fedora:latest

RUN dnf update -y

RUN dnf install -y  cmake \
                    gcc-c++ \
                    clang \
                    environment-modules \
                    openmpi-devel
