
FROM fedora:latest

RUN dnf update -y

RUN dnf install -y  cmake \
                    git \
                    gcc-c++ \
                    make \
                    clang \
                    environment-modules \
                    openmpi-devel \
                    mpich-devel \
                    lcov gcovr
